refresh_rate: 1 seconds
appenders:
  stdout:
    kind: console
  logfile:
    kind: file
    path: "main.log"
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S.%6f)} {l}: {m}{n}"
root:
  level: info
  appenders:
    # - stdout
    - logfile
