[package]
name = "fuzzy_attempt"
version = "0.1.0"
authors = ["neil"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = "1.0.0"
plotlib = "0.5.1"
chrono = "0.4"
